version: '3.8'

services:
  my-postgres:
    image: postgres:9.6.19
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
    - target: 5432
      published: 5432
      protocol: tcp
      mode: host


  postgres-adminer:
    image: adminer
    container_name: my_postgres_adminer
    restart: always
    ports:
    - 9091:8080